default:
  app:
    name: Streetlights MQTT API
    version: 1.0.0

  broker:
    mqtt:
      url: mqtt://test.mosquitto.org:1883
      topics: ["smartylighting/streetlights/1/0/action/+/turn/on"]
      qos:
      protocol: mqtt
      retain:
      subscribe: true

development:

test:

staging:

production:
